apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: rpoojitha04/frontend:v1
      ports:
        - containerPort: 80
